# ruff: noqa: D101, ERA001, E501
# generated by datamodel-codegen:
#   filename:  swagger.yml
#   timestamp: 2024-07-21T19:34:06+00:00
#   version:   0.25.8

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, RootModel


class Action(Enum):
    delete = "delete"
    update = "update"


class Alias(BaseModel):
    """An alias model, which can be associated with a series, season, movie, person, or list."""

    language: str | None = Field(
        default=None,
        description="A 3-4 character string indicating the language of the alias, as defined in Language.",
        max_length=4,
    )
    name: str | None = Field(default=None, description="A string containing the alias itself.", max_length=100)


class ArtworkBaseRecord(BaseModel):
    """base artwork record."""

    height: int | None = Field(default=None, json_schema_extra={"x-go-name": "Height"})
    id: int | None = None
    image: str | None = Field(default=None, json_schema_extra={"x-go-name": "Image"})
    includes_text: bool | None = Field(default=None, alias="includesText")
    language: str | None = None
    score: float | None = None
    thumbnail: str | None = Field(default=None, json_schema_extra={"x-go-name": "Thumbnail"})
    type: int | None = Field(
        default=None,
        description="The artwork type corresponds to the ids from the /artwork/types endpoint.",
        json_schema_extra={"x-go-name": "Type"},
    )
    width: int | None = Field(default=None, json_schema_extra={"x-go-name": "Width"})


class ArtworkExtendedRecord(BaseModel):
    """extended artwork record."""

    episode_id: int | None = Field(default=None, alias="episodeId")
    height: int | None = Field(default=None, json_schema_extra={"x-go-name": "Height"})
    id: int | None = Field(default=None, json_schema_extra={"x-go-name": "ID"})
    image: str | None = Field(default=None, json_schema_extra={"x-go-name": "Image"})
    includes_text: bool | None = Field(default=None, alias="includesText")
    language: str | None = None
    movie_id: int | None = Field(default=None, alias="movieId")
    network_id: int | None = Field(default=None, alias="networkId")
    people_id: int | None = Field(default=None, alias="peopleId")
    score: float | None = None
    season_id: int | None = Field(default=None, alias="seasonId")
    series_id: int | None = Field(default=None, alias="seriesId")
    series_people_id: int | None = Field(default=None, alias="seriesPeopleId")
    status: ArtworkStatus | None = None
    tag_options: list[TagOption] | None = Field(
        default=None, alias="tagOptions", json_schema_extra={"x-go-name": "TagOptions"}
    )
    thumbnail: str | None = Field(default=None, json_schema_extra={"x-go-name": "Thumbnail"})
    thumbnail_height: int | None = Field(
        default=None,
        alias="thumbnailHeight",
        json_schema_extra={"x-go-name": "ThumbnailHeight"},
    )
    thumbnail_width: int | None = Field(
        default=None,
        alias="thumbnailWidth",
        json_schema_extra={"x-go-name": "ThumbnailWidth"},
    )
    type: int | None = Field(
        default=None,
        description="The artwork type corresponds to the ids from the /artwork/types endpoint.",
        json_schema_extra={"x-go-name": "Type"},
    )
    updated_at: int | None = Field(default=None, alias="updatedAt", json_schema_extra={"x-go-name": "UpdatedAt"})
    width: int | None = Field(default=None, json_schema_extra={"x-go-name": "Width"})


class ArtworkIdExtendedGetResponse(BaseModel):
    data: ArtworkExtendedRecord | None = None
    status: str | None = None


class ArtworkIdGetResponse(BaseModel):
    data: ArtworkBaseRecord | None = None
    status: str | None = None


class ArtworkStatus(BaseModel):
    """artwork status record."""

    id: int | None = Field(default=None, json_schema_extra={"x-go-name": "ID"})
    name: str | None = None


class ArtworkStatusesGetResponse(BaseModel):
    data: list[ArtworkStatus] | None = None
    status: str | None = None


class ArtworkType(BaseModel):
    """artwork type record."""

    height: int | None = None
    id: int | None = Field(default=None, json_schema_extra={"x-go-name": "ID"})
    image_format: str | None = Field(
        default=None,
        alias="imageFormat",
        json_schema_extra={"x-go-name": "ImageFormat"},
    )
    name: str | None = Field(default=None, json_schema_extra={"x-go-name": "Name"})
    record_type: str | None = Field(default=None, alias="recordType", json_schema_extra={"x-go-name": "RecordType"})
    slug: str | None = Field(default=None, json_schema_extra={"x-go-name": "Slug"})
    thumb_height: int | None = Field(
        default=None,
        alias="thumbHeight",
        json_schema_extra={"x-go-name": "ThumbHeight"},
    )
    thumb_width: int | None = Field(default=None, alias="thumbWidth", json_schema_extra={"x-go-name": "ThumbWidth"})
    width: int | None = Field(default=None, json_schema_extra={"x-go-name": "Width"})


class ArtworkTypesGetResponse(BaseModel):
    data: list[ArtworkType] | None = None
    status: str | None = None


class AwardBaseRecord(BaseModel):
    """base award record."""

    id: int | None = None
    name: str | None = None


class AwardCategoryBaseRecord(BaseModel):
    """base award category record."""

    allow_co_nominees: bool | None = Field(
        default=None,
        alias="allowCoNominees",
        json_schema_extra={"x-go-name": "AllowCoNominees"},
    )
    award: AwardBaseRecord | None = None
    for_movies: bool | None = Field(default=None, alias="forMovies", json_schema_extra={"x-go-name": "ForMovies"})
    for_series: bool | None = Field(default=None, alias="forSeries", json_schema_extra={"x-go-name": "ForSeries"})
    id: int | None = Field(default=None, json_schema_extra={"x-go-name": "ID"})
    name: str | None = None


class AwardCategoryExtendedRecord(BaseModel):
    """extended award category record."""

    allow_co_nominees: bool | None = Field(
        default=None,
        alias="allowCoNominees",
        json_schema_extra={"x-go-name": "AllowCoNominees"},
    )
    award: AwardBaseRecord | None = None
    for_movies: bool | None = Field(default=None, alias="forMovies", json_schema_extra={"x-go-name": "ForMovies"})
    for_series: bool | None = Field(default=None, alias="forSeries", json_schema_extra={"x-go-name": "ForSeries"})
    id: int | None = Field(default=None, json_schema_extra={"x-go-name": "ID"})
    name: str | None = None
    nominees: list[AwardNomineeBaseRecord] | None = Field(default=None, json_schema_extra={"x-go-name": "Nominees"})


class AwardExtendedRecord(BaseModel):
    """extended award record."""

    categories: list[AwardCategoryBaseRecord] | None = Field(
        default=None, json_schema_extra={"x-go-name": "Categories"}
    )
    id: int | None = None
    name: str | None = None
    score: int | None = Field(default=None, json_schema_extra={"x-go-name": "Score"})


class AwardNomineeBaseRecord(BaseModel):
    """base award nominee record."""

    character: Character | None = None
    details: str | None = None
    episode: EpisodeBaseRecord | None = None
    id: int | None = Field(default=None, json_schema_extra={"x-go-name": "ID"})
    is_winner: bool | None = Field(default=None, alias="isWinner", json_schema_extra={"x-go-name": "IsWinner"})
    movie: MovieBaseRecord | None = None
    series: SeriesBaseRecord | None = None
    year: str | None = None
    category: str | None = None
    name: str | None = None


class AwardsCategoriesIdExtendedGetResponse(BaseModel):
    data: AwardCategoryExtendedRecord | None = None
    status: str | None = None


class AwardsCategoriesIdGetResponse(BaseModel):
    data: AwardCategoryBaseRecord | None = None
    status: str | None = None


class AwardsGetResponse(BaseModel):
    data: list[AwardBaseRecord] | None = None
    status: str | None = None


class AwardsIdExtendedGetResponse(BaseModel):
    data: AwardExtendedRecord | None = None
    status: str | None = None


class AwardsIdGetResponse(BaseModel):
    data: AwardBaseRecord | None = None
    status: str | None = None


class Biography(BaseModel):
    """biography record."""

    biography: str | None = Field(default=None, json_schema_extra={"x-go-name": "Biography"})
    language: str | None = Field(default=None, json_schema_extra={"x-go-name": "Language"})


class Character(BaseModel):
    """character record."""

    aliases: list[Alias] | None = Field(default=None, json_schema_extra={"x-go-name": "Aliases"})
    episode: RecordInfo | None = None
    episode_id: int | None = Field(default=None, alias="episodeId")
    id: int | None = Field(default=None, json_schema_extra={"x-go-name": "ID"})
    image: str | None = None
    is_featured: bool | None = Field(default=None, alias="isFeatured", json_schema_extra={"x-go-name": "IsFeatured"})
    movie_id: int | None = Field(default=None, alias="movieId")
    movie: RecordInfo | None = None
    name: str | None = None
    name_translations: list[str] | None = Field(
        default=None,
        alias="nameTranslations",
        json_schema_extra={"x-go-name": "NameTranslations"},
    )
    overview_translations: list[str] | None = Field(
        default=None,
        alias="overviewTranslations",
        json_schema_extra={"x-go-name": "OverviewTranslations"},
    )
    people_id: int | None = Field(default=None, alias="peopleId")
    person_img_url: str | None = Field(default=None, alias="personImgURL")
    people_type: str | None = Field(default=None, alias="peopleType")
    series_id: int | None = Field(default=None, alias="seriesId")
    series: RecordInfo | None = None
    sort: int | None = Field(default=None, json_schema_extra={"x-go-name": "Sort"})
    tag_options: list[TagOption] | None = Field(
        default=None, alias="tagOptions", json_schema_extra={"x-go-name": "TagOptions"}
    )
    type: int | None = Field(default=None, json_schema_extra={"x-go-name": "Type"})
    url: str | None = Field(default=None, json_schema_extra={"x-go-name": "URL"})
    person_name: str | None = Field(default=None, alias="personName")


class CharactersIdGetResponse(BaseModel):
    data: Character | None = None
    status: str | None = None


class Companies(BaseModel):
    """Companies by type record."""

    studio: list[Company] | None = None
    network: list[Company] | None = None
    production: list[Company] | None = None
    distributor: list[Company] | None = None
    special_effects: list[Company] | None = None


class CompaniesGetResponse(BaseModel):
    data: list[Company] | None = None
    status: str | None = None
    links: Links | None = None


class CompaniesIdGetResponse(BaseModel):
    data: Company | None = None
    status: str | None = None


class CompaniesTypesGetResponse(BaseModel):
    data: list[CompanyType] | None = None
    status: str | None = None


class Company(BaseModel):
    """A company record."""

    active_date: str | None = Field(default=None, alias="activeDate")
    aliases: list[Alias] | None = Field(default=None, json_schema_extra={"x-go-name": "Aliases"})
    country: str | None = None
    id: int | None = Field(default=None, json_schema_extra={"x-go-name": "ID"})
    inactive_date: str | None = Field(default=None, alias="inactiveDate")
    name: str | None = None
    name_translations: list[str] | None = Field(
        default=None,
        alias="nameTranslations",
        json_schema_extra={"x-go-name": "NameTranslations"},
    )
    overview_translations: list[str] | None = Field(
        default=None,
        alias="overviewTranslations",
        json_schema_extra={"x-go-name": "OverviewTranslations"},
    )
    primary_company_type: int | None = Field(
        default=None,
        alias="primaryCompanyType",
        json_schema_extra={"x-go-name": "PrimaryCompanyType"},
    )
    slug: str | None = Field(default=None, json_schema_extra={"x-go-name": "Slug"})
    parent_company: ParentCompany | None = Field(default=None, alias="parentCompany")
    tag_options: list[TagOption] | None = Field(
        default=None, alias="tagOptions", json_schema_extra={"x-go-name": "TagOptions"}
    )


class CompanyRelationShip(BaseModel):
    """A company relationship."""

    id: int | None = None
    type_name: str | None = Field(default=None, alias="typeName")


class CompanyType(BaseModel):
    """A company type record."""

    company_type_id: int | None = Field(default=None, alias="companyTypeId")
    company_type_name: str | None = Field(default=None, alias="companyTypeName")


class ContentRating(BaseModel):
    """content rating record."""

    id: int | None = Field(default=None, json_schema_extra={"x-go-name": "ID"})
    name: str | None = Field(default=None, json_schema_extra={"x-go-name": "Name"})
    description: str | None = None
    country: str | None = None
    content_type: str | None = Field(default=None, alias="contentType")
    order: int | None = None
    full_name: str | None = Field(default=None, alias="fullName")


class ContentRatingsGetResponse(BaseModel):
    data: list[ContentRating] | None = None
    status: str | None = None


class CountriesGetResponse(BaseModel):
    data: list[Country] | None = None
    status: str | None = None


class Country(BaseModel):
    """country record."""

    id: str | None = Field(default=None, json_schema_extra={"x-go-name": "ID"})
    name: str | None = Field(default=None, json_schema_extra={"x-go-name": "Name"})
    short_code: str | None = Field(default=None, alias="shortCode", json_schema_extra={"x-go-name": "ShortCode"})


class Data(BaseModel):
    token: str | None = None


class Data1(BaseModel):
    series: SeriesBaseRecord | None = None
    episodes: list[EpisodeBaseRecord] | None = None


class Data2(BaseModel):
    series: SeriesBaseRecord | None = None


class EntitiesGetResponse(BaseModel):
    data: list[EntityType] | None = None
    status: str | None = None


class Entity(BaseModel):
    """Entity record."""

    movie_id: int | None = Field(default=None, alias="movieId")
    order: int | None = Field(default=None, json_schema_extra={"x-go-name": "Order"})
    series_id: int | None = Field(default=None, alias="seriesId")


class EntityType(BaseModel):
    """Entity Type record."""

    id: int | None = None
    name: str | None = Field(default=None, json_schema_extra={"x-go-name": "Order"})
    has_specials: bool | None = Field(default=None, alias="hasSpecials")


class EntityUpdate(BaseModel):
    """entity update record."""

    entity_type: str | None = Field(default=None, alias="entityType", json_schema_extra={"x-go-name": "EnitityType"})
    method_int: int | None = Field(default=None, alias="methodInt")
    method: str | None = Field(default=None, json_schema_extra={"x-go-name": "Method"})
    extra_info: str | None = Field(default=None, alias="extraInfo")
    user_id: int | None = Field(default=None, alias="userId")
    record_type: str | None = Field(default=None, alias="recordType")
    record_id: int | None = Field(default=None, alias="recordId", json_schema_extra={"x-go-name": "RecordID"})
    time_stamp: int | None = Field(default=None, alias="timeStamp", json_schema_extra={"x-go-name": "TimeStamp"})
    series_id: int | None = Field(
        default=None,
        alias="seriesId",
        description="Only present for episodes records",
        json_schema_extra={"x-go-name": "RecordID"},
    )
    merge_to_id: int | None = Field(default=None, alias="mergeToId")
    merge_to_entity_type: str | None = Field(default=None, alias="mergeToEntityType")


class EpisodeBaseRecord(BaseModel):
    """base episode record."""

    absolute_number: int | None = Field(default=None, alias="absoluteNumber")
    aired: str | None = None
    airs_after_season: int | None = Field(default=None, alias="airsAfterSeason")
    airs_before_episode: int | None = Field(default=None, alias="airsBeforeEpisode")
    airs_before_season: int | None = Field(default=None, alias="airsBeforeSeason")
    finale_type: str | None = Field(default=None, alias="finaleType", description="season, midseason, or series")
    id: int | None = Field(default=None, json_schema_extra={"x-go-name": "ID"})
    image: str | None = None
    image_type: int | None = Field(default=None, alias="imageType")
    is_movie: int | None = Field(default=None, alias="isMovie", json_schema_extra={"x-go-name": "IsMovie"})
    last_updated: str | None = Field(default=None, alias="lastUpdated")
    linked_movie: int | None = Field(default=None, alias="linkedMovie")
    name: str | None = None
    name_translations: list[str] | None = Field(
        default=None,
        alias="nameTranslations",
        json_schema_extra={"x-go-name": "NameTranslations"},
    )
    number: int | None = None
    overview: str | None = None
    overview_translations: list[str] | None = Field(
        default=None,
        alias="overviewTranslations",
        json_schema_extra={"x-go-name": "OverviewTranslations"},
    )
    runtime: int | None = None
    season_number: int | None = Field(default=None, alias="seasonNumber")
    seasons: list[SeasonBaseRecord] | None = Field(default=None, json_schema_extra={"x-go-name": "Seasons"})
    series_id: int | None = Field(default=None, alias="seriesId", json_schema_extra={"x-go-name": "SeriesID"})
    season_name: str | None = Field(default=None, alias="seasonName")
    year: str | None = None


class EpisodeExtendedRecord(BaseModel):
    """extended episode record."""

    aired: str | None = None
    airs_after_season: int | None = Field(default=None, alias="airsAfterSeason")
    airs_before_episode: int | None = Field(default=None, alias="airsBeforeEpisode")
    airs_before_season: int | None = Field(default=None, alias="airsBeforeSeason")
    awards: list[AwardBaseRecord] | None = Field(default=None, json_schema_extra={"x-go-name": "Awards"})
    characters: list[Character] | None = Field(default=None, json_schema_extra={"x-go-name": "Characters"})
    companies: list[Company] | None = None
    content_ratings: list[ContentRating] | None = Field(
        default=None,
        alias="contentRatings",
        json_schema_extra={"x-go-name": "ContentRatings"},
    )
    finale_type: str | None = Field(default=None, alias="finaleType", description="season, midseason, or series")
    id: int | None = Field(default=None, json_schema_extra={"x-go-name": "ID"})
    image: str | None = None
    image_type: int | None = Field(default=None, alias="imageType")
    is_movie: int | None = Field(default=None, alias="isMovie", json_schema_extra={"x-go-name": "IsMovie"})
    last_updated: str | None = Field(default=None, alias="lastUpdated")
    linked_movie: int | None = Field(default=None, alias="linkedMovie")
    name: str | None = None
    name_translations: list[str] | None = Field(
        default=None,
        alias="nameTranslations",
        json_schema_extra={"x-go-name": "NameTranslations"},
    )
    networks: list[Company] | None = None
    nominations: list[AwardNomineeBaseRecord] | None = Field(default=None, json_schema_extra={"x-go-name": "Nominees"})
    number: int | None = None
    overview: str | None = None
    overview_translations: list[str] | None = Field(
        default=None,
        alias="overviewTranslations",
        json_schema_extra={"x-go-name": "OverviewTranslations"},
    )
    production_code: str | None = Field(default=None, alias="productionCode")
    remote_ids: list[RemoteID] | None = Field(
        default=None, alias="remoteIds", json_schema_extra={"x-go-name": "RemoteIDs"}
    )
    runtime: int | None = None
    season_number: int | None = Field(default=None, alias="seasonNumber")
    seasons: list[SeasonBaseRecord] | None = Field(default=None, json_schema_extra={"x-go-name": "Seasons"})
    series_id: int | None = Field(default=None, alias="seriesId", json_schema_extra={"x-go-name": "SeriesID"})
    studios: list[Company] | None = None
    tag_options: list[TagOption] | None = Field(
        default=None, alias="tagOptions", json_schema_extra={"x-go-name": "TagOptions"}
    )
    trailers: list[Trailer] | None = Field(default=None, json_schema_extra={"x-go-name": "Trailers"})
    translations: TranslationExtended | None = None
    year: str | None = None


class EpisodesGetResponse(BaseModel):
    data: list[EpisodeBaseRecord] | None = None
    status: str | None = None
    links: Links | None = None


class EpisodesIdExtendedGetResponse(BaseModel):
    data: EpisodeExtendedRecord | None = None
    status: str | None = None


class EpisodesIdGetResponse(BaseModel):
    data: EpisodeBaseRecord | None = None
    status: str | None = None


class EpisodesIdTranslationsLanguageGetResponse(BaseModel):
    data: Translation | None = None
    status: str | None = None


class FavoriteRecord(BaseModel):
    """Favorites record."""

    series: int | None = Field(default=None, json_schema_extra={"x-go-name": "series"})
    movie: int | None = Field(default=None, json_schema_extra={"x-go-name": "movies"})
    episode: int | None = Field(default=None, json_schema_extra={"x-go-name": "episodes"})
    artwork: int | None = Field(default=None, json_schema_extra={"x-go-name": "artwork"})
    people: int | None = Field(default=None, json_schema_extra={"x-go-name": "people"})
    list: int | None = Field(default=None, json_schema_extra={"x-go-name": "list"})


class Favorites(BaseModel):
    """User favorites record."""

    series: list[int] | None = Field(default=None, json_schema_extra={"x-go-name": "series"})
    movies: list[int] | None = Field(default=None, json_schema_extra={"x-go-name": "movies"})
    episodes: list[int] | None = Field(default=None, json_schema_extra={"x-go-name": "episodes"})
    artwork: list[int] | None = Field(default=None, json_schema_extra={"x-go-name": "artwork"})
    people: list[int] | None = Field(default=None, json_schema_extra={"x-go-name": "people"})
    lists: list[int] | None = Field(default=None, json_schema_extra={"x-go-name": "list"})


class Gender(BaseModel):
    """gender record."""

    id: int | None = Field(default=None, json_schema_extra={"x-go-name": "ID"})
    name: str | None = Field(default=None, json_schema_extra={"x-go-name": "Name"})


class GendersGetResponse(BaseModel):
    data: list[Gender] | None = None
    status: str | None = None


class Genre(Enum):
    number_1 = 1
    number_2 = 2
    number_3 = 3
    number_4 = 4
    number_5 = 5
    number_6 = 6
    number_7 = 7
    number_8 = 8
    number_9 = 9
    number_10 = 10
    number_11 = 11
    number_12 = 12
    number_13 = 13
    number_14 = 14
    number_15 = 15
    number_16 = 16
    number_17 = 17
    number_18 = 18
    number_19 = 19
    number_21 = 21
    number_22 = 22
    number_23 = 23
    number_24 = 24
    number_25 = 25
    number_26 = 26
    number_27 = 27
    number_28 = 28
    number_29 = 29
    number_30 = 30
    number_31 = 31
    number_32 = 32
    number_33 = 33
    number_34 = 34
    number_35 = 35
    number_36 = 36


class GenreBaseRecord(BaseModel):
    """base genre record."""

    id: int | None = Field(default=None, json_schema_extra={"x-go-name": "ID"})
    name: str | None = Field(default=None, json_schema_extra={"x-go-name": "Name"})
    slug: str | None = Field(default=None, json_schema_extra={"x-go-name": "Slug"})


class GenresGetResponse(BaseModel):
    data: list[GenreBaseRecord] | None = None
    status: str | None = None


class GenresIdGetResponse(BaseModel):
    data: GenreBaseRecord | None = None
    status: str | None = None


class Inspiration(BaseModel):
    """Movie inspiration record."""

    id: int | None = Field(default=None, json_schema_extra={"x-go-name": "ID"})
    type: str | None = None
    type_name: str | None = None
    url: str | None = None


class InspirationType(BaseModel):
    """Movie inspiration type record."""

    id: int | None = Field(default=None, json_schema_extra={"x-go-name": "ID"})
    name: str | None = None
    description: str | None = None
    reference_name: str | None = None
    url: str | None = None


class InspirationTypesGetResponse(BaseModel):
    data: list[InspirationType] | None = None
    status: str | None = None


class Language(BaseModel):
    """language record."""

    id: str | None = Field(default=None, json_schema_extra={"x-go-name": "ID"})
    name: str | None = Field(default=None, json_schema_extra={"x-go-name": "Name"})
    native_name: str | None = Field(default=None, alias="nativeName", json_schema_extra={"x-go-name": "NativeName"})
    short_code: str | None = Field(default=None, alias="shortCode")


class LanguagesGetResponse(BaseModel):
    data: list[Language] | None = None
    status: str | None = None


class Links(BaseModel):
    """Links for next, previous and current record."""

    prev: str | None = None
    self: str | None = None
    next: str | None = None
    total_items: int | None = None
    page_size: int | None = None


class ListBaseRecord(BaseModel):
    """base list record."""

    aliases: list[Alias] | None = Field(default=None, json_schema_extra={"x-go-name": "Aliases"})
    id: int | None = Field(default=None, json_schema_extra={"x-go-name": "ID"})
    image: str | None = None
    image_is_fallback: bool | None = Field(default=None, alias="imageIsFallback")
    is_official: bool | None = Field(default=None, alias="isOfficial", json_schema_extra={"x-go-name": "IsOfficial"})
    name: str | None = None
    name_translations: list[str] | None = Field(
        default=None,
        alias="nameTranslations",
        json_schema_extra={"x-go-name": "NameTranslations"},
    )
    overview: str | None = None
    overview_translations: list[str] | None = Field(
        default=None,
        alias="overviewTranslations",
        json_schema_extra={"x-go-name": "OverviewTranslations"},
    )
    remote_ids: list[RemoteID] | None = Field(
        default=None, alias="remoteIds", json_schema_extra={"x-go-name": "RemoteIDs"}
    )
    tags: list[TagOption] | None = Field(default=None, json_schema_extra={"x-go-name": "TagOptions"})
    score: int | None = None
    url: str | None = None


class ListExtendedRecord(BaseModel):
    """extended list record."""

    aliases: list[Alias] | None = Field(default=None, json_schema_extra={"x-go-name": "Aliases"})
    entities: list[Entity] | None = Field(default=None, json_schema_extra={"x-go-name": "Entities"})
    id: int | None = Field(default=None, json_schema_extra={"x-go-name": "ID"})
    image: str | None = None
    image_is_fallback: bool | None = Field(default=None, alias="imageIsFallback")
    is_official: bool | None = Field(default=None, alias="isOfficial", json_schema_extra={"x-go-name": "IsOfficial"})
    name: str | None = None
    name_translations: list[str] | None = Field(
        default=None,
        alias="nameTranslations",
        json_schema_extra={"x-go-name": "NameTranslations"},
    )
    overview: str | None = None
    overview_translations: list[str] | None = Field(
        default=None,
        alias="overviewTranslations",
        json_schema_extra={"x-go-name": "OverviewTranslations"},
    )
    score: int | None = Field(default=None, json_schema_extra={"x-go-name": "Score"})
    url: str | None = None


class ListsGetResponse(BaseModel):
    data: list[ListBaseRecord] | None = None
    status: str | None = None
    links: Links | None = None


class ListsIdExtendedGetResponse(BaseModel):
    data: ListExtendedRecord | None = None
    status: str | None = None


class ListsIdGetResponse(BaseModel):
    data: ListBaseRecord | None = None
    status: str | None = None


class ListsIdTranslationsLanguageGetResponse(BaseModel):
    data: list[Translation] | None = None
    status: str | None = None


class ListsSlugSlugGetResponse(ListsIdGetResponse):
    pass


class LoginPostRequest(BaseModel):
    apikey: str
    pin: str | None = None


class LoginPostResponse(BaseModel):
    data: Data | None = None
    status: str | None = None


class Meta(Enum):
    translations = "translations"


class Meta3(Enum):
    translations = "translations"
    episodes = "episodes"


class MovieBaseRecord(BaseModel):
    """base movie record."""

    aliases: list[Alias] | None = Field(default=None, json_schema_extra={"x-go-name": "Aliases"})
    id: int = Field(json_schema_extra={"x-go-name": "ID"})
    image: str | None = Field(default=None, json_schema_extra={"x-go-name": "Image"})
    last_updated: str | None = Field(default=None, alias="lastUpdated")
    name: str | None = Field(default=None, json_schema_extra={"x-go-name": "Name"})
    name_translations: list[str] | None = Field(
        default=None,
        alias="nameTranslations",
        json_schema_extra={"x-go-name": "NameTranslations"},
    )
    overview_translations: list[str] | None = Field(
        default=None,
        alias="overviewTranslations",
        json_schema_extra={"x-go-name": "OverviewTranslations"},
    )
    score: float | None = Field(default=None, json_schema_extra={"x-go-name": "Score"})
    slug: str | None = Field(default=None, json_schema_extra={"x-go-name": "Slug"})
    status: Status | None = None
    runtime: int | None = None
    year: str | None = None


class MovieExtendedRecord(BaseModel):
    """extended movie record."""

    aliases: list[Alias] | None = Field(default=None, json_schema_extra={"x-go-name": "Aliases"})
    artworks: list[ArtworkBaseRecord] | None = Field(default=None, json_schema_extra={"x-go-name": "Artworks"})
    audio_languages: list[str] | None = Field(
        default=None,
        alias="audioLanguages",
        json_schema_extra={"x-go-name": "AudioLanguages"},
    )
    awards: list[AwardBaseRecord] | None = Field(default=None, json_schema_extra={"x-go-name": "Awards"})
    box_office: str | None = Field(default=None, alias="boxOffice")
    box_office_us: str | None = Field(default=None, alias="boxOfficeUS")
    budget: str | None = None
    characters: list[Character] | None = Field(default=None, json_schema_extra={"x-go-name": "Characters"})
    companies: Companies | None = None
    content_ratings: list[ContentRating] | None = Field(default=None, alias="contentRatings")
    first_release: Release | None = None
    genres: list[GenreBaseRecord] | None = Field(default=None, json_schema_extra={"x-go-name": "Genres"})
    id: int = Field(default=None, json_schema_extra={"x-go-name": "ID"})
    image: str | None = Field(default=None, json_schema_extra={"x-go-name": "Image"})
    inspirations: list[Inspiration] | None = Field(default=None, json_schema_extra={"x-go-name": "Inspirations"})
    last_updated: str | None = Field(default=None, alias="lastUpdated")
    lists: list[ListBaseRecord] | None = None
    name: str | None = Field(default=None, json_schema_extra={"x-go-name": "Name"})
    name_translations: list[str] | None = Field(
        default=None,
        alias="nameTranslations",
        json_schema_extra={"x-go-name": "NameTranslations"},
    )
    original_country: str | None = Field(default=None, alias="originalCountry")
    original_language: str | None = Field(default=None, alias="originalLanguage")
    overview_translations: list[str] | None = Field(
        default=None,
        alias="overviewTranslations",
        json_schema_extra={"x-go-name": "OverviewTranslations"},
    )
    production_countries: list[ProductionCountry] | None = Field(
        default=None, json_schema_extra={"x-go-name": "ProductionCountries"}
    )
    releases: list[Release] | None = Field(default=None, json_schema_extra={"x-go-name": "Releases"})
    remote_ids: list[RemoteID] | None = Field(
        default=None, alias="remoteIds", json_schema_extra={"x-go-name": "RemoteIDs"}
    )
    runtime: int | None = None
    score: float | None = Field(default=None, json_schema_extra={"x-go-name": "Score"})
    slug: str | None = Field(default=None, json_schema_extra={"x-go-name": "Slug"})
    spoken_languages: list[str] | None = Field(default=None, json_schema_extra={"x-go-name": "SpokenLanguages"})
    status: Status | None = None
    studios: list[StudioBaseRecord] | None = Field(default=None, json_schema_extra={"x-go-name": "Studios"})
    subtitle_languages: list[str] | None = Field(
        default=None,
        alias="subtitleLanguages",
        json_schema_extra={"x-go-name": "SubtitleLanguages"},
    )
    tag_options: list[TagOption] | None = Field(
        default=None, alias="tagOptions", json_schema_extra={"x-go-name": "TagOptions"}
    )
    trailers: list[Trailer] | None = Field(default=None, json_schema_extra={"x-go-name": "Trailers"})
    translations: TranslationExtended | None = None
    year: str | None = None


class MoviesFilterGetResponse(BaseModel):
    data: list[MovieBaseRecord] | None = None
    status: str | None = None


class MoviesGetResponse(BaseModel):
    data: list[MovieBaseRecord] | None = None
    status: str | None = None
    links: Links | None = None


class MoviesIdExtendedGetResponse(BaseModel):
    data: MovieExtendedRecord | None = None
    status: str | None = None


class MoviesIdGetResponse(BaseModel):
    data: MovieBaseRecord | None = None
    status: str | None = None


class MoviesIdTranslationsLanguageGetResponse(EpisodesIdTranslationsLanguageGetResponse):
    pass


class MoviesSlugSlugGetResponse(MoviesIdGetResponse):
    pass


class MoviesStatusesGetResponse(BaseModel):
    data: list[Status] | None = None
    status: str | None = None


class ParentCompany(BaseModel):
    """A parent company record."""

    id: int | None = None
    name: str | None = None
    relation: CompanyRelationShip | None = None


class PeopleBaseRecord(BaseModel):
    """base people record."""

    aliases: list[Alias] | None = Field(default=None, json_schema_extra={"x-go-name": "Aliases"})
    id: int | None = Field(default=None, json_schema_extra={"x-go-name": "ID"})
    image: str | None = None
    last_updated: str | None = Field(default=None, alias="lastUpdated")
    name: str | None = None
    name_translations: list[str] | None = Field(
        default=None,
        alias="nameTranslations",
        json_schema_extra={"x-go-name": "NameTranslations"},
    )
    overview_translations: list[str] | None = Field(
        default=None,
        alias="overviewTranslations",
        json_schema_extra={"x-go-name": "OverviewTranslations"},
    )
    score: int | None = Field(default=None, json_schema_extra={"x-go-name": "Score"})


class PeopleExtendedRecord(BaseModel):
    """extended people record."""

    aliases: list[Alias] | None = Field(default=None, json_schema_extra={"x-go-name": "Aliases"})
    awards: list[AwardBaseRecord] | None = Field(default=None, json_schema_extra={"x-go-name": "Awards"})
    biographies: list[Biography] | None = Field(default=None, json_schema_extra={"x-go-name": "Biographies"})
    birth: str | None = None
    birth_place: str | None = Field(default=None, alias="birthPlace")
    characters: list[Character] | None = Field(default=None, json_schema_extra={"x-go-name": "Characters"})
    death: str | None = None
    gender: int | None = None
    id: int | None = Field(default=None, json_schema_extra={"x-go-name": "ID"})
    image: str | None = None
    last_updated: str | None = Field(default=None, alias="lastUpdated")
    name: str | None = None
    name_translations: list[str] | None = Field(
        default=None,
        alias="nameTranslations",
        json_schema_extra={"x-go-name": "NameTranslations"},
    )
    overview_translations: list[str] | None = Field(
        default=None,
        alias="overviewTranslations",
        json_schema_extra={"x-go-name": "OverviewTranslations"},
    )
    races: list[Race] | None = Field(default=None, json_schema_extra={"x-go-name": "Races"})
    remote_ids: list[RemoteID] | None = Field(
        default=None, alias="remoteIds", json_schema_extra={"x-go-name": "RemoteIDs"}
    )
    score: int | None = Field(default=None, json_schema_extra={"x-go-name": "Score"})
    slug: str | None = None
    tag_options: list[TagOption] | None = Field(
        default=None, alias="tagOptions", json_schema_extra={"x-go-name": "TagOptions"}
    )
    translations: TranslationExtended | None = None


class PeopleGetResponse(BaseModel):
    data: list[PeopleBaseRecord] | None = None
    status: str | None = None
    links: Links | None = None


class PeopleIdExtendedGetResponse(BaseModel):
    data: PeopleExtendedRecord | None = None
    status: str | None = None


class PeopleIdGetResponse(BaseModel):
    data: PeopleBaseRecord | None = None
    status: str | None = None


class PeopleIdTranslationsLanguageGetResponse(EpisodesIdTranslationsLanguageGetResponse):
    pass


class PeopleType(BaseModel):
    """people type record."""

    id: int | None = Field(default=None, json_schema_extra={"x-go-name": "ID"})
    name: str | None = Field(default=None, json_schema_extra={"x-go-name": "Name"})


class PeopleTypesGetResponse(BaseModel):
    data: list[PeopleType] | None = None
    status: str | None = None


class ProductionCountry(BaseModel):
    """Production country record."""

    id: int | None = Field(default=None, json_schema_extra={"x-go-name": "ID"})
    country: str | None = None
    name: str | None = None


class Race(BaseModel):
    """race record."""


class RecordInfo(BaseModel):
    """base record info."""

    image: str | None = Field(default=None, json_schema_extra={"x-go-name": "Image"})
    name: str | None = Field(default=None, json_schema_extra={"x-go-name": "Name"})
    year: str | None = None


class Release(BaseModel):
    """release record."""

    country: str | None = None
    date: str | None = None
    detail: str | None = None


class RemoteID(BaseModel):
    """remote id record."""

    id: str | None = Field(default=None, json_schema_extra={"x-go-name": "ID"})
    type: int | None = Field(default=None, json_schema_extra={"x-go-name": "Type"})
    source_name: str | None = Field(default=None, alias="sourceName", json_schema_extra={"x-go-name": "SourceName"})


class SearchByRemoteIdResult(BaseModel):
    """search by remote reuslt is a base record for a movie, series, people, season or company search result."""

    series: SeriesBaseRecord | None = None
    people: PeopleBaseRecord | None = None
    movie: MovieBaseRecord | None = None
    episode: EpisodeBaseRecord | None = None
    company: Company | None = None


class SearchGetResponse(BaseModel):
    data: list[SearchResult] | None = None
    status: str | None = None
    links: Links | None = None


class SearchRemoteidRemoteIdGetResponse(BaseModel):
    data: list[SearchByRemoteIdResult] | None = None
    status: str | None = None


class SearchResult(BaseModel):
    """search result."""

    aliases: list[str] | None = None
    companies: list[str] | None = None
    company_type: str | None = Field(default=None, alias="companyType")
    country: str | None = None
    director: str | None = None
    first_air_time: str | None = None
    genres: list[str] | None = None
    id: str
    image_url: str | None = None
    name: str | None = None
    is_official: bool | None = None
    name_translated: str | None = None
    network: str | None = None
    object_id: str = Field(alias="objectID")
    official_list: str | None = Field(default=None, alias="officialList")
    overview: str | None = None
    overviews: TranslationSimple | None = None
    overview_translated: list[str] | None = None
    poster: str | None = None
    posters: list[str] | None = None
    primary_language: str | None = None
    remote_ids: list[RemoteID] | None = Field(default=None, json_schema_extra={"x-go-name": "RemoteIDs"})
    status: str | None = Field(default=None, json_schema_extra={"x-go-name": "Status"})
    slug: str | None = None
    studios: list[str] | None = None
    title: str | None = None
    thumbnail: str | None = None
    translations: TranslationSimple | None = None
    translations_with_lang: list[str] | None = Field(default=None, alias="translationsWithLang")
    tvdb_id: str | None = None
    type: str | None = None
    year: str | None = None


class SeasonBaseRecord(BaseModel):
    """season genre record."""

    id: int
    image: str | None = None
    image_type: int | None = Field(default=None, alias="imageType")
    last_updated: str | None = Field(default=None, alias="lastUpdated")
    name: str | None = None
    name_translations: list[str] | None = Field(
        default=None,
        alias="nameTranslations",
        json_schema_extra={"x-go-name": "NameTranslations"},
    )
    number: int | None = Field(default=None, json_schema_extra={"x-go-name": "Number"})
    overview_translations: list[str] | None = Field(
        default=None,
        alias="overviewTranslations",
        json_schema_extra={"x-go-name": "OverviewTranslations"},
    )
    companies: Companies | None = None
    series_id: int | None = Field(default=None, alias="seriesId", json_schema_extra={"x-go-name": "SeriesID"})
    type: SeasonType | None = None
    year: str | None = None


class SeasonExtendedRecord(BaseModel):
    """extended season record."""

    artwork: list[ArtworkBaseRecord] | None = Field(default=None, json_schema_extra={"x-go-name": "Artwork"})
    companies: Companies | None = None
    episodes: list[EpisodeBaseRecord] | None = Field(default=None, json_schema_extra={"x-go-name": "Episodes"})
    id: int
    image: str | None = None
    image_type: int | None = Field(default=None, alias="imageType")
    last_updated: str | None = Field(default=None, alias="lastUpdated")
    name: str | None = None
    name_translations: list[str] | None = Field(
        default=None,
        alias="nameTranslations",
        json_schema_extra={"x-go-name": "NameTranslations"},
    )
    number: int | None = Field(default=None, json_schema_extra={"x-go-name": "Number"})
    overview_translations: list[str] | None = Field(
        default=None,
        alias="overviewTranslations",
        json_schema_extra={"x-go-name": "OverviewTranslations"},
    )
    series_id: int | None = Field(default=None, alias="seriesId", json_schema_extra={"x-go-name": "SeriesID"})
    trailers: list[Trailer] | None = Field(default=None, json_schema_extra={"x-go-name": "Trailers"})
    type: SeasonType | None = None
    tag_options: list[TagOption] | None = Field(
        default=None, alias="tagOptions", json_schema_extra={"x-go-name": "TagOptions"}
    )
    translations: list[Translation] | None = None
    year: str | None = None


class SeasonType(BaseModel):
    """season type record."""

    alternate_name: str | None = Field(default=None, alias="alternateName", json_schema_extra={"x-go-name": "Name"})
    id: int | None = Field(default=None, json_schema_extra={"x-go-name": "ID"})
    name: str | None = Field(default=None, json_schema_extra={"x-go-name": "Name"})
    type: str | None = Field(default=None, json_schema_extra={"x-go-name": "Type"})


class SeasonsGetResponse(BaseModel):
    data: list[SeasonBaseRecord] | None = None
    status: str | None = None


class SeasonsIdExtendedGetResponse(BaseModel):
    data: SeasonExtendedRecord | None = None
    status: str | None = None


class SeasonsIdGetResponse(BaseModel):
    data: SeasonBaseRecord | None = None
    status: str | None = None


class SeasonsIdTranslationsLanguageGetResponse(EpisodesIdTranslationsLanguageGetResponse):
    pass


class SeasonsTypesGetResponse(BaseModel):
    data: list[SeasonType] | None = None
    status: str | None = None


class SeriesAirsDays(BaseModel):
    """A series airs day record."""

    friday: bool | None = Field(default=None, json_schema_extra={"x-go-name": "Friday"})
    monday: bool | None = Field(default=None, json_schema_extra={"x-go-name": "Monday"})
    saturday: bool | None = Field(default=None, json_schema_extra={"x-go-name": "Saturday"})
    sunday: bool | None = Field(default=None, json_schema_extra={"x-go-name": "Sunday"})
    thursday: bool | None = Field(default=None, json_schema_extra={"x-go-name": "Thursday"})
    tuesday: bool | None = Field(default=None, json_schema_extra={"x-go-name": "Tuesday"})
    wednesday: bool | None = Field(default=None, json_schema_extra={"x-go-name": "Wednesday"})


class SeriesBaseRecord(BaseModel):
    """The base record for a series. All series airs time like firstAired, lastAired, nextAired, etc. are in US EST for US series, and for all non-US series, the time of the show's country capital or most populous city. For streaming services, is the official release time. See https://support.thetvdb.com/kb/faq.php?id=29."""

    aliases: list[Alias] | None = Field(default=None, json_schema_extra={"x-go-name": "Aliases"})
    average_runtime: int | None = Field(default=None, alias="averageRuntime")
    country: str | None = None
    default_season_type: int | None = Field(
        default=None,
        alias="defaultSeasonType",
        json_schema_extra={"x-go-name": "DefaultSeasonType"},
    )
    episodes: list[EpisodeBaseRecord] | None = Field(default=None, json_schema_extra={"x-go-name": "Episodes"})
    first_aired: str | None = Field(default=None, alias="firstAired")
    id: int
    image: str | None = None
    is_order_randomized: bool | None = Field(
        default=None,
        alias="isOrderRandomized",
        json_schema_extra={"x-go-name": "IsOrderRandomized"},
    )
    last_aired: str | None = Field(default=None, alias="lastAired")
    last_updated: str | None = Field(default=None, alias="lastUpdated")
    name: str | None = None
    name_translations: list[str] | None = Field(
        default=None,
        alias="nameTranslations",
        json_schema_extra={"x-go-name": "NameTranslations"},
    )
    next_aired: str | None = Field(default=None, alias="nextAired", json_schema_extra={"x-go-name": "NextAired"})
    original_country: str | None = Field(default=None, alias="originalCountry")
    original_language: str | None = Field(default=None, alias="originalLanguage")
    overview_translations: list[str] | None = Field(
        default=None,
        alias="overviewTranslations",
        json_schema_extra={"x-go-name": "OverviewTranslations"},
    )
    score: float | None = Field(default=None, json_schema_extra={"x-go-name": "Score"})
    slug: str | None = None
    status: Status | None = None
    year: str | None = None


class SeriesExtendedRecord(BaseModel):
    """The extended record for a series. All series airs time like firstAired, lastAired, nextAired, etc. are in US EST for US series, and for all non-US series, the time of the show's country capital or most populous city. For streaming services, is the official release time. See https://support.thetvdb.com/kb/faq.php?id=29."""

    abbreviation: str | None = None
    airs_days: SeriesAirsDays | None = Field(default=None, alias="airsDays")
    airs_time: str | None = Field(default=None, alias="airsTime")
    aliases: list[Alias] | None = Field(default=None, json_schema_extra={"x-go-name": "Aliases"})
    artworks: list[ArtworkExtendedRecord] | None = Field(default=None, json_schema_extra={"x-go-name": "Artworks"})
    average_runtime: int | None = Field(default=None, alias="averageRuntime")
    characters: list[Character] | None = Field(default=None, json_schema_extra={"x-go-name": "Characters"})
    content_ratings: list[ContentRating] | None = Field(default=None, alias="contentRatings")
    country: str | None = None
    default_season_type: int | None = Field(
        default=None,
        alias="defaultSeasonType",
        json_schema_extra={"x-go-name": "DefaultSeasonType"},
    )
    episodes: list[EpisodeBaseRecord] | None = Field(default=None, json_schema_extra={"x-go-name": "Episodes"})
    first_aired: str | None = Field(default=None, alias="firstAired")
    lists: list[ListBaseRecord] | None = None
    genres: list[GenreBaseRecord] | None = Field(default=None, json_schema_extra={"x-go-name": "Genres"})
    id: int
    image: str | None = None
    is_order_randomized: bool | None = Field(
        default=None,
        alias="isOrderRandomized",
        json_schema_extra={"x-go-name": "IsOrderRandomized"},
    )
    last_aired: str | None = Field(default=None, alias="lastAired")
    last_updated: str | None = Field(default=None, alias="lastUpdated")
    name: str | None = None
    name_translations: list[str] | None = Field(
        default=None,
        alias="nameTranslations",
        json_schema_extra={"x-go-name": "NameTranslations"},
    )
    companies: list[Company] | None = None
    next_aired: str | None = Field(default=None, alias="nextAired", json_schema_extra={"x-go-name": "NextAired"})
    original_country: str | None = Field(default=None, alias="originalCountry")
    original_language: str | None = Field(default=None, alias="originalLanguage")
    original_network: Company | None = Field(default=None, alias="originalNetwork")
    overview: str | None = None
    latest_network: Company | None = Field(default=None, alias="latestNetwork")
    overview_translations: list[str] | None = Field(
        default=None,
        alias="overviewTranslations",
        json_schema_extra={"x-go-name": "OverviewTranslations"},
    )
    remote_ids: list[RemoteID] | None = Field(
        default=None, alias="remoteIds", json_schema_extra={"x-go-name": "RemoteIDs"}
    )
    score: float | None = Field(default=None, json_schema_extra={"x-go-name": "Score"})
    seasons: list[SeasonBaseRecord] | None = Field(default=None, json_schema_extra={"x-go-name": "Seasons"})
    season_types: list[SeasonType] | None = Field(
        default=None, alias="seasonTypes", json_schema_extra={"x-go-name": "Seasons"}
    )
    slug: str | None = None
    status: Status | None = None
    tags: list[TagOption] | None = Field(default=None, json_schema_extra={"x-go-name": "TagOptions"})
    trailers: list[Trailer] | None = Field(default=None, json_schema_extra={"x-go-name": "Trailers"})
    translations: TranslationExtended | None = None
    year: str | None = None


class SeriesFilterGetResponse(BaseModel):
    data: list[SeriesBaseRecord] | None = None


class SeriesGetResponse(BaseModel):
    data: list[SeriesBaseRecord] | None = None
    status: str | None = None
    links: Links | None = None


class SeriesIdArtworksGetResponse(BaseModel):
    data: SeriesExtendedRecord | None = None
    status: str | None = None


class SeriesIdEpisodesSeasonTypeGetResponse(BaseModel):
    data: Data1 | None = None
    status: str | None = None


class SeriesIdEpisodesSeasonTypeLangGetResponse(BaseModel):
    data: Data2 | None = None
    status: str | None = None


class SeriesIdExtendedGetResponse(SeriesIdArtworksGetResponse):
    pass


class SeriesIdGetResponse(BaseModel):
    data: SeriesBaseRecord | None = None
    status: str | None = None


class SeriesIdNextAiredGetResponse(SeriesIdGetResponse):
    pass


class SeriesIdTranslationsLanguageGetResponse(EpisodesIdTranslationsLanguageGetResponse):
    pass


class SeriesSlugSlugGetResponse(SeriesIdGetResponse):
    pass


class SeriesStatusesGetResponse(MoviesStatusesGetResponse):
    pass


class Short(Enum):
    boolean_true = True
    boolean_false = False


class Sort(Enum):
    score = "score"
    first_aired = "firstAired"
    name_ = "name"


class Sort1(Enum):
    score = "score"
    first_aired = "firstAired"
    last_aired = "lastAired"
    name_ = "name"


class SortType(Enum):
    asc = "asc"
    desc = "desc"


class SourceType(BaseModel):
    """source type record."""

    id: int | None = Field(default=None, json_schema_extra={"x-go-name": "ID"})
    name: str | None = Field(default=None, json_schema_extra={"x-go-name": "Name"})
    postfix: str | None = None
    prefix: str | None = None
    slug: str | None = Field(default=None, json_schema_extra={"x-go-name": "Slug"})
    sort: int | None = Field(default=None, json_schema_extra={"x-go-name": "Sort"})


class SourcesTypesGetResponse(BaseModel):
    data: list[SourceType] | None = None
    status: str | None = None


class Status(BaseModel):
    """status record."""

    id: int | None = Field(default=None, json_schema_extra={"x-go-name": "ID"})
    keep_updated: bool | None = Field(
        default=None,
        alias="keepUpdated",
        json_schema_extra={"x-go-name": "KeepUpdated"},
    )
    name: str | None = Field(default=None, json_schema_extra={"x-go-name": "Name"})
    record_type: str | None = Field(default=None, alias="recordType", json_schema_extra={"x-go-name": "RecordType"})


class Status1(Enum):
    number_1 = 1
    number_2 = 2
    number_3 = 3


class StudioBaseRecord(BaseModel):
    """studio record."""

    id: int | None = Field(default=None, json_schema_extra={"x-go-name": "ID"})
    name: str | None = Field(default=None, json_schema_extra={"x-go-name": "Name"})
    parent_studio: int | None = Field(default=None, alias="parentStudio")


class Tag(BaseModel):
    """tag record."""

    allows_multiple: bool | None = Field(
        default=None,
        alias="allowsMultiple",
        json_schema_extra={"x-go-name": "AllowsMultiple"},
    )
    help_text: str | None = Field(default=None, alias="helpText")
    id: int | None = Field(default=None, json_schema_extra={"x-go-name": "ID"})
    name: str | None = Field(default=None, json_schema_extra={"x-go-name": "Name"})
    options: list[TagOption] | None = Field(default=None, json_schema_extra={"x-go-name": "TagOptions"})


class TagOption(BaseModel):
    """tag option record."""

    help_text: str | None = Field(default=None, alias="helpText")
    id: int | None = Field(default=None, json_schema_extra={"x-go-name": "ID"})
    name: str | None = Field(default=None, json_schema_extra={"x-go-name": "Name"})
    tag: int | None = Field(default=None, json_schema_extra={"x-go-name": "Tag"})
    tag_name: str | None = Field(default=None, alias="tagName", json_schema_extra={"x-go-name": "TagName"})


class TagOptionEntity(BaseModel):
    """a entity with selected tag option."""

    name: str | None = None
    tag_name: str | None = Field(default=None, alias="tagName")
    tag_id: int | None = Field(default=None, alias="tagId")


class Trailer(BaseModel):
    """trailer record."""

    id: int | None = Field(default=None, json_schema_extra={"x-go-name": "ID"})
    language: str | None = None
    name: str | None = None
    url: str | None = None
    runtime: int | None = None


class Translation(BaseModel):
    """translation record."""

    aliases: list[str] | None = None
    is_alias: bool | None = Field(default=None, alias="isAlias")
    is_primary: bool | None = Field(default=None, alias="isPrimary")
    language: str | None = Field(default=None, json_schema_extra={"x-go-name": "Language"})
    name: str | None = None
    overview: str | None = None
    tagline: str | None = Field(
        default=None,
        description="Only populated for movie translations.  We disallow taglines without a title.",
    )


class TranslationExtended(BaseModel):
    """translation extended record."""

    name_translations: list[Translation] | None = Field(default=None, alias="nameTranslations")
    overview_translations: list[Translation] | None = Field(default=None, alias="overviewTranslations")
    alias: list[str] | None = None


class TranslationSimple(RootModel[dict[str, str] | None]):
    """translation simple record."""

    root: dict[str, str] | None = None


class Type(Enum):
    artwork = "artwork"
    award_nominees = "award_nominees"
    companies = "companies"
    episodes = "episodes"
    lists = "lists"
    people = "people"
    seasons = "seasons"
    series = "series"
    seriespeople = "seriespeople"
    artworktypes = "artworktypes"
    award_categories = "award_categories"
    awards = "awards"
    company_types = "company_types"
    content_ratings = "content_ratings"
    countries = "countries"
    entity_types = "entity_types"
    genres = "genres"
    languages = "languages"
    movies = "movies"
    movie_genres = "movie_genres"
    movie_status = "movie_status"
    peopletypes = "peopletypes"
    seasontypes = "seasontypes"
    sourcetypes = "sourcetypes"
    tag_options = "tag_options"
    tags = "tags"
    translatedcharacters = "translatedcharacters"
    translatedcompanies = "translatedcompanies"
    translatedepisodes = "translatedepisodes"
    translatedlists = "translatedlists"
    translatedmovies = "translatedmovies"
    translatedpeople = "translatedpeople"
    translatedseasons = "translatedseasons"
    translatedserierk = "translatedserierk"


class UpdatesGetResponse(BaseModel):
    data: list[EntityUpdate] | None = None
    status: str | None = None
    links: Links | None = None


class UserFavoritesGetResponse(BaseModel):
    data: list[Favorites] | None = None
    status: str | None = None


class UserGetResponse(BaseModel):
    data: list[UserInfo] | None = None
    status: str | None = None


class UserIdGetResponse(UserGetResponse):
    pass


class UserInfo(BaseModel):
    """User info record."""

    id: int | None = None
    language: str | None = None
    name: str | None = None
    type: str | None = None
