"""Fix id is not unique

Revision ID: 526fbc726d80
Revises: 8fc4b07d9adc
Create Date: 2024-07-26 17:55:32.326226
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "526fbc726d80"
down_revision: str | None = "8fc4b07d9adc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("series", sa.Column("tvdb_id", sa.Integer(), nullable=False), sa.PrimaryKeyConstraint("tvdb_id"))
    op.drop_table("shows")
    op.add_column("episodes", sa.Column("series_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "episodes", "series", ["series_id"], ["tvdb_id"])
    op.drop_column("episodes", "show_id")
    op.add_column(
        "user_list_items",
        sa.Column("kind", sa.Enum("SERIES", "MOVIE", "EPISODE", name="userlistitemkind"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_list_items", "kind")
    op.add_column("episodes", sa.Column("show_id", sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, "episodes", "shows", ["show_id"], ["tvdb_id"])
    op.drop_column("episodes", "series_id")
    op.create_table("shows", sa.Column("tvdb_id", sa.INTEGER(), nullable=False), sa.PrimaryKeyConstraint("tvdb_id"))
    op.drop_table("series")
    # ### end Alembic commands ###
