# Pre-commit configuration.
# See https://github.com/python-discord/code-jam-template/tree/main#pre-commit-run-linting-before-committing

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        description: Run ruff linter
        entry: poetry run ruff check --force-exclude
        language: system
        types_or: [python, pyi]
        require_serial: true
        args: [--fix, --exit-non-zero-on-fix]

  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        description: Run ruff formatter
        entry: poetry run ruff format
        language: system
        types_or: [python, pyi]
        require_serial: true

  - repo: local
    hooks:
      - id: basedpyright
        name: Based Pyright
        description: Run basedpyright type checker
        entry: poetry run basedpyright --warnings
        language: system
        types: [python]
        pass_filenames: false # pyright runs for the entire project, it can't run for single files
