cogs:
  - courageous_comets.cogs.about
  - courageous_comets.cogs.keywords.search_command
  - courageous_comets.cogs.keywords.search_context_menu
  - courageous_comets.cogs.keywords.topics_command
  - courageous_comets.cogs.keywords.user_context_menu
  - courageous_comets.cogs.messages
  - courageous_comets.cogs.ping
  - courageous_comets.cogs.sentiment.message_context_menu
  - courageous_comets.cogs.sentiment.search_command
  - courageous_comets.cogs.sentiment.search_context_menu
  - courageous_comets.cogs.sentiment.user_context_menu
  - courageous_comets.cogs.frequency
dev-cogs:
  - jishaku
nltk:
  - punkt
  - stopwords
  - vader_lexicon
transformers:
  - sentence-transformers/all-MiniLM-L6-v2
