name: Build Devcontainer

on:
  push:
    branches:
      - main
    paths:
      - .devcontainer/**/*
      - .github/workflows/build-devcontainer.yaml

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build devcontainer image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/thijsfranck/courageous-comets-devcontainer
          cacheFrom: ghcr.io/thijsfranck/courageous-comets-devcontainer
          push: always
