name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis/redis-stack:7.2.0-v11
        ports:
          - 6379:6379
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      BOT_CONFIG_PATH: ${{ github.workspace }}/application.yaml
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      NLTK_DATA: ${{ github.workspace }}/nltk_data
      SENTENCE_TRANSFORMERS_HOME: ${{ github.workspace }}/hf_data

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up caching for NLTK_DATA
        uses: actions/cache@v4
        with:
          path: ${{ env.NLTK_DATA }}
          key: ${{ runner.os }}-nltk-data-${{ hashFiles(env.BOT_CONFIG_PATH) }}
          restore-keys: |
            ${{ runner.os }}-nltk-data-

      - name: Set up caching for SENTENCE_TRANSFORMERS_HOME
        uses: actions/cache@v4
        with:
          path: ${{ env.SENTENCE_TRANSFORMERS_HOME }}
          key: ${{ runner.os }}-hf-data-${{ hashFiles(env.BOT_CONFIG_PATH) }}
          restore-keys: |
            ${{ runner.os }}-hf-data-

      - name: Setup Python, Poetry and dependencies
        uses: packetcoders/action-setup-cache-python-poetry@main
        with:
          python-version: 3.12
          poetry-version: 1.8.3

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1

      - name: Set up Pyright
        run: echo "$(poetry env info --path)/bin" >> $GITHUB_PATH
        shell: bash

      - name: Run type checking
        uses: jakebailey/pyright-action@v2
        with:
          version: 1.1.370
          python-version: 3.12

      - name: Run tests
        run: poetry run pytest
        shell: bash
